name 'rundeck'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures rundeck'
long_description 'Installs/Configures rundeck'
version '0.1.0'

depends 'apt'
depends 'java'
depends 'mysql'
depends 'database'
depends 'apache2'
