
default['rundeck']['version'] = '2.4.2-1'
default['rundeck']['database_root_password'] = 'password'
default['rundeck']['database'] = 'rundeck'
default['rundeck']['database_user'] = 'rundeck'
default['rundeck']['database_password'] = 'password'
default['rundeck']['database_server'] = 'localhost'
default['rundeck']['apps_server'] = 'localhost'
default['rundeck']['domain_name'] = 'rundeck.dev'
default['rundeck']['ssh_user'] = 'rundeck'
default['rundeck']['ssh_key_path'] = '/var/lib/rundeck/.ssh/id_rsa'
